### ISSUE TITLE
Bug - The link to the latest version returns the old version (6.4.1)

### ISSUE THREAD

**Issue by dr47** [znuny/Znuny4OTRS-QuickClose#10]
### Environment

- Framework version: 6.5.1

### Expected behavior

Link https://addons.znuny.com/api/addon_repos/public/2401/latest return latest version.

### Actual behavior

Link returns 6.4.1 version.

### How to reproduce
```
$ /opt/otrs/bin/otrs.Console.pl Admin::Package::Install https://addons.znuny.com/api/addon_repos/public/2401:latest
Installing package...
ERROR: OTRS-otrs.Console.pl-Admin::Package::Install-10 Perl: 5.32.1 OS: linux Time: Mon Apr 10 16:31:27 2023

 Message: Sorry, can't install/upgrade package, because the framework version required by the package (6.4.x;) does not match your Framework (6.5.1)!
```

or

```
$ wget -qO - https://addons.znuny.com/api/addon_repos/public/2401/latest | egrep "<Version|<Framework"
    <Version>6.4.1</Version>
    <Framework>6.4.x</Framework>
```

**Comment by NiklasSchmitt** [comment]
Hi @dr47,
thanks a lot for letting us know about that.
There is still the wrong ID placed in the URL. The correct URL for version 6.5 should be: `https://addons.znuny.com/api/addon_repos/public/2738/latest`. I have updated also the URL in the README.md in commit https://github.com/znuny/Znuny4OTRS-QuickClose/commit/af119b939fabdb6e27ae7f0c5bc0005a49f269ee.

Best regards,
Niklas :coffee:
