### ISSUE TITLE
German translation ("erfolgreich schließen")

### ISSUE THREAD

**Issue by pajz** [znuny/Znuny4OTRS-QuickClose#7]
Hmm, are you sure "erfolgreich schließen" is the best translation of "Quick Close"? "Erfolgreich geschlossen" ("Closed Successful") is one of the default ticket states, but "Quick Close" could just as well be associated with a different state, in which case the current translation seems somewhat misleading to me. How about "sofort schließen", "ohne Notiz schließen" (both even shorter) or ""ohne Begründung schließen"?

**Comment by thorsteneckel** [comment]
Hi @pajz ! Thanks for your feedback. You're right, we fixed this in the versions 1.4.2 and 1.3.3 of Znuny4OTRS-QuickClose. 

Greetings,
  Thorsten
